(in-package :vgm)

(defun read-vgm-header (stream)
  "Read a vgm header from a stream."
  (make-vgm-header
   :fcc-vgm              (read-u32 stream)
   :lng-eof-offset       (read-u32 stream)
   :lng-version          (read-u32 stream)
   :lng-hz-psg           (read-u32 stream)
   :lng-hz-ym2413        (read-u32 stream)
   :lng-gd3-offset       (read-u32 stream)
   :lng-total-samples    (read-u32 stream)
   :lng-loop-offset      (read-u32 stream)
   :lng-loop-samples     (read-u32 stream)
   :lng-rate             (read-u32 stream)
   :sht-psg-feedback     (read-u16 stream)
   :byt-psg-sr-width     (read-u32 stream)
   :byt-psg-flags        (read-u32 stream)
   :lng-hz-ym2612        (read-u32 stream)
   :lng-hz-ym2151        (read-u32 stream)
   :lng-data-offset      (read-u32 stream)
   :lng-hz-spcm          (read-u32 stream)
   :lng-spcm-intf        (read-u32 stream)
   :lng-hz-rf5c68        (read-u32 stream)
   :lng-hz-ym2203        (read-u32 stream)
   :lng-hz-ym2608        (read-u32 stream)
   :lng-hz-ym2610        (read-u32 stream)
   :lng-hz-ym3812        (read-u32 stream)
   :lng-hz-ym3526        (read-u32 stream)
   :lng-hz-y8950         (read-u32 stream)
   :lng-hz-ymf262        (read-u32 stream)
   :lng-hz-ymf278b       (read-u32 stream)
   :lng-hz-ymf271        (read-u32 stream)
   :lng-hz-ymz280b       (read-u32 stream)
   :lng-hz-rf5c164       (read-u32 stream)
   :lng-hz-pwm           (read-u32 stream)
   :lng-hz-ay8910        (read-u32 stream)
   :byt-ay-type          (read-u8 stream)
   :byt-ay-flag          (read-u8 stream)
   :byt-ay-flag-ym2203   (read-u8 stream)
   :byt-ay-flag-ym2608   (read-u8 stream)
   :byt-volume-modifier  (read-u8 stream)
   :byt-reserved-2       (read-u8 stream)
   :byt-loop-base        (read-u8 stream)
   :byt-loop-modifier    (read-u8 stream)
   :lng-hz-gb-dmg        (read-u32 stream)
   :lng-hz-nes-apu       (read-u32 stream)
   :lng-hz-multi-pcm     (read-u32 stream)
   :lng-hz-upd7759       (read-u32 stream)
   :lng-hz-okim6258      (read-u32 stream)
   :byt-oki6258-flags    (read-u8 stream)
   :byt-k054539-flags    (read-u8 stream)
   :byt-c140-type        (read-u8 stream)
   :byt-reserved-flags   (read-u8 stream)
   :lng-hz-okim6295      (read-u32 stream)
   :lng-hz-k051649       (read-u32 stream)
   :lng-hz-k054539       (read-u32 stream)
   :lng-hz-huc6280       (read-u32 stream)
   :lng-hz-c140          (read-u32 stream)
   :lng-hz-k053260       (read-u32 stream)
   :lng-hz-pokey         (read-u32 stream)
   :lng-hz-qsound        (read-u32 stream)
   :lng-hz-scsp          (read-u32 stream)
   :lng-extra-offset     (read-u32 stream)
   :lng-hz-wswan         (read-u32 stream)
   :lng-hz-vsu           (read-u32 stream)
   :lng-hz-saa1099       (read-u32 stream)
   :lng-hz-es5503        (read-u32 stream)
   :lng-hz-es5506        (read-u32 stream)
   :byt-es5503-chns      (read-u8 stream)
   :byt-es5506-chns      (read-u8 stream)
   :byt-c352-clk-div     (read-u8 stream)
   :byt-es-reserved      (read-u8 stream)
   :lng-hz-x1-010        (read-u32 stream)
   :lng-hz-c352          (read-u32 stream)
   :lng-hz-ga20          (read-u32 stream)))

(defun read-vgm-file (stream)
  "Read vgm data from a stream."
  nil)

(defun load-vgm-file (filespec)
  "Load a vgm file."
  (with-open-binary-file (input filespec)
    (read-vgm-file input)))
