(in-package :vgm)

;; copied from https://github.com/vgmrips/vgmplay/blob/master/VGMPlay/VGMFile.h

(defconstant +volume-modif-wrap+ #xc0)
(defconstant +fcc-vgm+ #x206d6756) ; "Vgm "
(defconstant +fcc-gd3+ #x20336447) ; "Gd3 "

(deftype fcc-vgm ()
  `(eql ,+fcc-vgm+))

(defstruct vgm-header
  (fcc-vgm              0 :type fcc-vgm)
  (lng-eof-offset       0 :type (unsigned-byte 32))
  (lng-version          0 :type (unsigned-byte 32))
  (lng-hz-psg           0 :type (unsigned-byte 32))
  (lng-hz-ym2413        0 :type (unsigned-byte 32))
  (lng-gd3-offset       0 :type (unsigned-byte 32))
  (lng-total-samples    0 :type (unsigned-byte 32))
  (lng-loop-offset      0 :type (unsigned-byte 32))
  (lng-loop-samples     0 :type (unsigned-byte 32))
  (lng-rate             0 :type (unsigned-byte 32))
  (sht-psg-feedback     0 :type (unsigned-byte 16))
  (byt-psg-sr-width     0 :type (unsigned-byte 8))
  (byt-psg-flags        0 :type (unsigned-byte 8))
  (lng-hz-ym2612        0 :type (unsigned-byte 32))
  (lng-hz-ym2151        0 :type (unsigned-byte 32))
  (lng-data-offset      0 :type (unsigned-byte 32))
  (lng-hz-spcm          0 :type (unsigned-byte 32))
  (lng-spcm-intf        0 :type (unsigned-byte 32))
  (lng-hz-rf5c68        0 :type (unsigned-byte 32))
  (lng-hz-ym2203        0 :type (unsigned-byte 32))
  (lng-hz-ym2608        0 :type (unsigned-byte 32))
  (lng-hz-ym2610        0 :type (unsigned-byte 32))
  (lng-hz-ym3812        0 :type (unsigned-byte 32))
  (lng-hz-ym3526        0 :type (unsigned-byte 32))
  (lng-hz-y8950         0 :type (unsigned-byte 32))
  (lng-hz-ymf262        0 :type (unsigned-byte 32))
  (lng-hz-ymf278b       0 :type (unsigned-byte 32))
  (lng-hz-ymf271        0 :type (unsigned-byte 32))
  (lng-hz-ymz280b       0 :type (unsigned-byte 32))
  (lng-hz-rf5c164       0 :type (unsigned-byte 32))
  (lng-hz-pwm           0 :type (unsigned-byte 32))
  (lng-hz-ay8910        0 :type (unsigned-byte 32))
  (byt-ay-type          0 :type (unsigned-byte 8))
  (byt-ay-flag          0 :type (unsigned-byte 8))
  (byt-ay-flag-ym2203   0 :type (unsigned-byte 8))
  (byt-ay-flag-ym2608   0 :type (unsigned-byte 8))
  (byt-volume-modifier  0 :type (unsigned-byte 8))
  (byt-reserved-2       0 :type (unsigned-byte 8))
  (byt-loop-base        0 :type (signed-byte 8))
  (byt-loop-modifier    0 :type (unsigned-byte 8))
  (lng-hz-gb-dmg        0 :type (unsigned-byte 32))
  (lng-hz-nes-apu       0 :type (unsigned-byte 32))
  (lng-hz-multi-pcm     0 :type (unsigned-byte 32))
  (lng-hz-upd7759       0 :type (unsigned-byte 32))
  (lng-hz-okim6258      0 :type (unsigned-byte 32))
  (byt-oki6258-flags    0 :type (unsigned-byte 8))
  (byt-k054539-flags    0 :type (unsigned-byte 8))
  (byt-c140-type        0 :type (unsigned-byte 8))
  (byt-reserved-flags   0 :type (unsigned-byte 8))
  (lng-hz-okim6295      0 :type (unsigned-byte 32))
  (lng-hz-k051649       0 :type (unsigned-byte 32))
  (lng-hz-k054539       0 :type (unsigned-byte 32))
  (lng-hz-huc6280       0 :type (unsigned-byte 32))
  (lng-hz-c140          0 :type (unsigned-byte 32))
  (lng-hz-k053260       0 :type (unsigned-byte 32))
  (lng-hz-pokey         0 :type (unsigned-byte 32))
  (lng-hz-qsound        0 :type (unsigned-byte 32))
  (lng-hz-scsp          0 :type (unsigned-byte 32))
  (lng-extra-offset     0 :type (unsigned-byte 32))
  (lng-hz-wswan         0 :type (unsigned-byte 32))
  (lng-hz-vsu           0 :type (unsigned-byte 32))
  (lng-hz-saa1099       0 :type (unsigned-byte 32))
  (lng-hz-es5503        0 :type (unsigned-byte 32))
  (lng-hz-es5506        0 :type (unsigned-byte 32))
  (byt-es5503-chns      0 :type (unsigned-byte 8))
  (byt-es5506-chns      0 :type (unsigned-byte 8))
  (byt-c352-clk-div     0 :type (unsigned-byte 8))
  (byt-es-reserved      0 :type (unsigned-byte 8))
  (lng-hz-x1-010        0 :type (unsigned-byte 32))
  (lng-hz-c352          0 :type (unsigned-byte 32))
  (lng-hz-ga20          0 :type (unsigned-byte 32)))

(defstruct vgm-hdr-extra
  (data-size        0 :type (unsigned-byte 32))
  (chp-2-clk-offset 0 :type (unsigned-byte 32))
  (chp-vol-offset   0 :type (unsigned-byte 32)))

(defstruct vgmx-chip-data-32
  (type 0 :type (unsigned-byte 8))
  (data 0 :type (unsigned-byte 32)))

(defstruct vgmx-chip-data-16
  (type  0 :type (unsigned-byte 8))
  (flags 0 :type (unsigned-byte 8))
  (data  0 :type (unsigned-byte 16)))

(defstruct vgmx-chp-extra-32
  (chip-cnt 0   :type (unsigned-byte 8))
  (ccdata   nil :type vgmx-chip-data-32))

(defstruct vgmx-chp-extra-16
  (chip-cnt 0   :type (unsigned-byte 8))
  (ccdata   nil :type vgmx-chip-data-16))

(defstruct gd3-tag
  (fcc-gd3           0 :type (unsigned-byte 32))
  (lng-version       0 :type (unsigned-byte 32))
  (lng-tag-length    0 :type (unsigned-byte 32))
  (str-track-name-e  0 :type string)
  (str-track-name-j  0 :type string)
  (str-game-name-e   0 :type string)
  (str-game-name-j   0 :type string)
  (str-system-name-e 0 :type string)
  (str-system-name-j 0 :type string)
  (str-author-name-e 0 :type string)
  (str-author-name-j 0 :type string)
  (str-release-date  0 :type string)
  (str-creator       0 :type string)
  (str-notes         0 :type string))

(defstruct vgm-pcm-data
  (data-size  0   :type (unsigned-byte 32))
  (data       nil :type (vector (unsigned-byte 8)))
  (data-start 0   :type (unsigned-byte 32)))

(defstruct vgm-pcm-bank
  (bank-count 0   :type (unsigned-byte 32))
  (bank       nil :type vgm-pcm-data)
  (data-size  0   :type (unsigned-byte 32))
  (data       nil :type (vector (unsigned-byte 8)))
  (data-pos   0   :type (unsigned-byte 32))
  (bnk-pos    0   :type (unsigned-byte 32)))
  
